version: "3.2"
services:
  app-server:
          #    image: amazing-application
          # Configuration for building the docker image for the backend service
          build:
            context: . # Use an image built from the specified dockerfile in the `polling-app-server` directory.
            dockerfile: ./amazing-application/Dockerfile
          ports:
            - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
          restart: always
          links:
            - amazing-redis
          depends_on:
            - amazing-db
            - amazing-redis
          env_file:
            - ./Docker/amazing-app/amazing-app.env
#    environment: # Pass environment variables to the service
#      SPRING_DATASOURCE_URL: dbc:postgresql://localhost:5432/${POSTGRES_DBNAME}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASS}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - default
  amazing-db:
    container_name: amazing-db
    image: postgres:latest
    env_file:
      - ./Docker/amazing-db/amazing-db.env
    ports:
      - 5433:5432
    volumes:
      - ./Docker/amazing-db/init_scripts/:/docker-entrypoint-initdb.d/
    networks:
      - default
  amazing-redis:
    container_name: amazing-cache
    image: redis:alpine
    hostname: redis
    env_file:
      - ./Docker/amazing-cache/amazing-cache.env
    ports:
      - 6379:6379
#    environment:
#      - REDIS_REPLICATION_MODE=master
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - default